### ISSUE TITLE
Add list of all tags into metadata

### ISSUE THREAD

**Issue by tunix** [totocaster/metalsmith-tags#12]
First of all thanks for this plugin! Just like creating pages for tags, I'd like to be able to construct a tag cloud. Would you be interested in exposing tags in metadata like below:

```
{...
    "tags": [
        "tech": {
            "path": "/blog/tags/tech",
            "posts": [
                {file},
                {file},
                ...
            ]
        },
        "linux": { ... }
    ]
...}
```

**Comment by hswolff** [comment]
This should now be possible via https://github.com/totocaster/metalsmith-tags/commit/f7b9b7236785369c03accaac09384100bb87b4b7. If you get the word cloud working please share what you did so I can add it to the readme!
