### ISSUE TITLE
Create tags as separate folder not file

### ISSUE THREAD

**Issue by s-stude** [totocaster/metalsmith-tags#2]
Hi,

Right now tags created like `files[opts.path + '/' + tag + '.html']`. 
What if to create them like `files[opts.path + '/' + tag + '/index.html']`? We can use some config option for that.

**Comment by mdotasia** [comment]
7a266aac4fb646adb09b513612d20e7b78b701e4 changed the default `opts.path` to `tags/:tag/index.html`. Given that Metalsmith's default is mapping `path/to/name.md` to `path/to/name.html`, I think the default should be `tags/:tag.html`. And whoever prefers `tags/:tag/index.html` applies `metalsmith-permalinks` as suggested by @totocaster. Then it would be more consistent.
