### ISSUE TITLE
multi-word tags should be hyphenated

### ISSUE THREAD

**Issue by oupala** [totocaster/metalsmith-tags#23]
With old version of metalsmith-tags (something like 0.6.x), multi-word tags were hyphenated :

the tag `my tag` would be converted to `my-tag`

With the last version of metalsmith-tags (0.10.x or 0.11.x), tags are not hyphenated any-more.

This causes some problem, espcially when linking to the tag page. The generated page is hypenated indeed : `topics/my-tag/index.html` whereas the link to this page is not hyphenated `topics/my tag/`.

This leads to invalid links.

As a consequence, the fix should hyphenate the link to the tag 'my-tag :

```html
<a href="/tags/my tag/">my tag</a>
```

should become :

```html
<a href="/tags/my-tag/">my tag</a>
```

The label `my tag` could also be converted to `my-tag` or not, I don't have any strong opinion on this.

**Comment by brianbrewer** [comment]
If you're using `Handlebars`, you can register a helper to make the strings safe for links (regex copied from lib/index.js):
```javascript
Handlebars.registerHelper("safe", function (context) {
    return context.replace(/ /g, '-');
});
```

And use it in a template (where **this** is the string with the tag name):
```handlebars
{{#each tags}}
    <a href="/tags/{{safe this}}">{{this}}</a>
{{/each}}
```

**Comment by oupala** [comment]
@brianbrewer I think that your answer is a workaround to make the plugin usable.

But I think this plugin should be usable by default, without the need of registering an additionnal helper.

**Comment by brianbrewer** [comment]
I completely understand, linking to a tag page is hassle without manipulating the tag string some other way, so I've [made a fork](https://github.com/brianbrewer/metalsmith-tags) and added a `hyphenate` option to set whether to hyphenate the multi-word tags or not. Currently it's default **false** to not break anything.

Using it should just be a case of:
```javascript
.use(tags({
    handle: 'tags',
    path:'topics/:tag.html',
    layout:'/partials/tag.hbt',
    sortBy: 'date',
    reverse: true,
    skipMetadata: false,
    hyphenate: true
  }));
```
Hopefully that should make all tags with spaces in them hyphenates at all points, I was thinking about maybe adding hyphenated and spaced tags to the metadata separately for completeness. I'll just mention @hswolff to get his opinion on this.

**Comment by oupala** [comment]
Your fork fixes the problem on my side, you should create a pull request as it should be merged.

Not only all tags with spaces should be hyphenated, but your option `hyphenate: true` should not be an option as the plugin **does not work** without it as long as some tags have spaces in them (and tags without spaces are not affected by this new behaviour).

**Comment by oupala** [comment]
I checked an old website generated by metalsmith and metalsmith-tags and it appears that the default behaviour of metalsmith-tags used to hypenate multi-word tags.

As a consequence, not hyphenatig multi-word tags is something I would call a bug.

**Comment by brianbrewer** [comment]
I see, I've looked through the changes made that affected this version 0.9.0, it looks #5 is a previous issue about how spaces are represented using `-` instead.

The suggested way to link to them is to rely on `path` metadata provided by **metalsmith-permalinks** and using the global `tags[tagname]` metadata to get to it, the reliance on the existence of a `path` metadata for each file is an assumption of the presence of **metalsmith-permalinks**.

I'm currently going through the process of changing the plugin so it uses hyphens as default, with some sort of `keepSpaces: true` option.

**Comment by oupala** [comment]
I'm hardly waiting for you pull request to be merged... :blush:

**Comment by oupala** [comment]
@brianbrewer your [previous comment](https://github.com/totocaster/metalsmith-tags/issues/23#issuecomment-135081137) makes me think about #21 and segmentio/metalsmith-permalinks#37.

I had suspected that metalsmith-permalinks and metalsmith-tags were closely tied. Do you know how they *should* be used ? In what order, with what configuration ?

**Comment by brianbrewer** [comment]
Really not sure, my configuration has `metalsmith-tags -> metalsmith-pagination -> metalsmith-permalinks` but in order to keep the `path` metadata for each file, I had to use the `skipMetadata: true` for metalsmith-tags

Sorry I couldn't be of more help

**Comment by oupala** [comment]
@brianbrewer I know that we're talking about something else than the main subject of this issue, but why would `metalsmith-tags` changes `path` metadata for each file?

**Comment by oupala** [comment]
Just to credit another plugin, this issue has been discovered adding the [metalsmith-broken-link-checker](/davidxmoody/metalsmith-broken-link-checker) plugin. It found some broken links and these links were all *tag related*.

Thanks for that @davidxmoody !

**Comment by hswolff** [comment]
So just pushed up `0.12.0` which offers a solution to this issue. I've added a new property for each page `tagsUrlSafe` which holds an array of url safe tag values.

See my usage of it on my blog: https://github.com/hswolff/blog/commit/29f779973a75b0929ae84fccd4076c3339c4747a

Another solution I was considering was to change the `tags` array to hold objects that looked something like:
```
{
   url: 'this-is-a-tag',
   display: 'this is a tag'
}
```

But I felt that would be a bigger change.

Let me know what you think!

**Comment by oupala** [comment]
Thank you @hswolff for fixing this bug. I can confirm that your fix is also fixing the bug on my side.

I just had to replace the `tags` tag by `tagsUrlSafe` in my handlebars templates.

I still wonder why you created another tag `tagsUrlSafe` and why not keep the old `tags` and fix its value?

What for is the old `tags` tag?

**Comment by hswolff** [comment]
For display purposes, that's what issue #5 was concerned with. If the tag name is `open source` then it should be displayed as `open source` in the page, but linked to as `open-source`. Hence the two arrays :)

**Comment by oupala** [comment]
Ok, I understand the point.

But I don't think it is a good idea.

If the tag name is `open source`, how can you be sure that it is one tag whose name is `open source`, or two tags `open` and `source`?

I don't mind as any solution is possible with your implementation. But I don't really see any usecase where issue #5 happens.

However, if someone created this issue, it means that he should have met this usecase...

And by the way, I don't have any opinion on what is the best solution between the current one, and *the other solution* you're talinkg about. I let you and other experts decide.

**Comment by hswolff** [comment]
Right now we're just using `,` to distinguish between different tags, so that's who we know. Yeah just trying to appease both use cases.
