### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by hswolff** [totocaster/metalsmith-tags#26]
Hello all,

I've switched my blog away from using metalsmith to render it, and as such will no longer be maintaining this project.

Looking for any maintainers to step up to champion this project forward.

-Harry

**Comment by almirfilho** [comment]
Hi, I volunteer =)

**Comment by hswolff** [comment]
Excited to hear the enthusiasm! Help out as new issues + PRs arrive for a little test drive and after things are looking good I'll add you as a contributor!

**Comment by samuelgoldenbaum** [comment]
Out of curiosity, why the move from metalsmith?

**Comment by hswolff** [comment]
I wrote about it in a [blog post](http://hswolff.com/blog/introducing-yarn/)! Hope that elucidates things!

**Comment by jarodtaylor** [comment]
@hswolff Are you still accepting pull requests for metalsmith-tags?

**Comment by hswolff** [comment]
I am. Provided a PR comes with passing tests I'll be happy to merge them. 

I'm looking for someone who has demonstrated at least 2 PRs merged in to transfer ownership to.

**Comment by jarodtaylor** [comment]
@hswolff thanks for the prompt reply.

I've made a [pull request](https://github.com/totocaster/metalsmith-tags/pull/34). Would love your thoughts/input. 

Thanks.

**Comment by mdotasia** [comment]
Would it be an option to move this repository over to @metalsmith and then try finding more maintainers for that group? I am not sure if Metalsmith can survive with crucial plugins being broken and not under the control of @metalsmith. cc @Ajedi32

**Comment by totocaster** [comment]
@mdotasia I'm open to this suggestion. Let's hear from @hswolff too since this plugin was mostly maintained by him.

**Comment by hswolff** [comment]
More than happy to move ownership of this repo to @metalsmith, whatever is best for the community.

**Comment by Ajedi32** [comment]
I'm a bit hesitant to take on new projects right now since I haven't had a whole lot of time to spend on Metalsmith lately as-is. That said, I'm certainly not the only one in the Metalsmith org, and it doesn't seem like `metalsmith-tags` is particularly high-maintenance, so if this project is currently unmaintained and you'd rather have us take over I'm okay with that...

**Comment by hswolff** [comment]
I'm not currently using metalsmith so not fully immersed in its uses. If everything thinks the best course is to move to the metalsmith org I'm all for that.

**Comment by hswolff** [comment]
Just realized I can't actually assign anyone else as a new maintainer, only @totocaster can.

If you're up to it I'd be happy to make @jarodtaylor the new maintainer of this project. Just requires @totocaster's help to do so. You've been adding some awesome PRs @jarodtaylor - thank you!

**Comment by totocaster** [comment]
Added @jarodtaylor! Thanks for all your work. /cc @hswolff

**Comment by jarodtaylor** [comment]
@hswolff @totocaster glad to help!

**Comment by ycherniavsky** [comment]
So, who is the current maintainer of `metalsmith-tags`? @jarodtaylor @hswolff @totocaster

**Comment by oupala** [comment]
It looks like the new maintainer is @jarodtaylor. Am I right?

**Comment by gijswijs** [comment]
I've submitted a PR last year, and haven't heard anything back yet. As is, this repository is not actively maintained.

**Comment by oupala** [comment]
According to @jarodtaylor's contribution graph, he is no more active on GitHub.

I think we should look for another maintainer. Let's ping all PR authors:

- @gijswijs
- @ycherniavskyi
- @wernerglinka
- @saschazar21
- @HenryMarshall
- @leviwheatcroft
- @jarodtaylor
- @tunix
- @rjpw
- @bobthecow
- @ceejbot
- @simbo
- @azurelogic
- @brianbrewer
- @iwootten
- @ronanguilloux
- @ekristen
- @paazmaya
- @belen-albeza
- @hswolff
- @sukima
- @dpobel
- @boushley
- @expalmer

And if you no longer use metalsmith or metalsmith-tags, sorry for the inconvenient ping.

**Comment by saschazar21** [comment]
Sorry if I'm disappointing somebody here, but I too am not using Metalsmith anymore.

However, I would be okay in reviewing newly opened PRs every now and then, if that is of help to anyone...

**Comment by oupala** [comment]
I also ping some people that have forked the project and commited to the fork:

- @anzfactory
- @rludgero
- @JonathanReeve
- @michaelkornblum
- @devlab21
- @MegaJ
- @wernerglinka
- @thinktandem
- @saschazar21
- @etnbrd
- @mpolitze
- @tiborsimon
- @byteclubfr

**Comment by gijswijs** [comment]
I'm ok with doing some maintenance on both metalsmith and metalsmith-tags. I'm just as busy as everybody else, but I can test and approve some PR's once a month. If that's enough of a commitment, you can count me in.

**Comment by oupala** [comment]
Good! 2 reviewer volounteered!

What do you think @totocaster and @jarodtaylor?

**Comment by totocaster** [comment]
I have to decline too. Haven't used metalsmith since 2014.

**Comment by neumannssg** [comment]
@totocaster I think you didn't have to decline anything. As the owner of this repo I think you are the one who can distribute the rights to someone else.

**Comment by totocaster** [comment]
@neumannssg I don't think "ownership" means anything in this case — I'm merely one who published it first, that's pretty much it. As for right — as stated above, I'm open to transfer repo to anyone that community decides is one who will take good care of the repo.

**Comment by oupala** [comment]
Thanks @totocaster, that's kind from you!

@gijswijs You can start to review issues and pull requests. You can also count on me to test features and bugfixes.
