### ISSUE TITLE
All tags metadata

### ISSUE THREAD

**Issue by almirfilho** [totocaster/metalsmith-tags#33]
It would be nice to have all (unique) tags of all files consolidated in an array.
Useful for generate a tag index page, or a tag cloud widget, or something similar.
(Particularly, I'm needing to generate a tag index page.)

__article1.md__ file:
```yaml
---
title: article 1
tags: tag-a, tag-b
---
...
```

__article2.md__ file:
```yaml
---
title: article 2
tags: tag-b, tag-c
---
...
```

In templates:
```javascript
console.log(allTags); // => ['tag-a', 'tag-b', 'tag-c']
```

What do you think about this feature, @totocaster and @hswolff?

**Comment by hswolff** [comment]
Sounds good to me. Would love to see a PR for what. Note that the list of tags would need to include the display tag along with the url friendly tag slug. Also be sure to include tests!

**Comment by almirfilho** [comment]
Ok! =)

**Comment by almirfilho** [comment]
Just realized that we already have this data and can access it by doing:

__with nunjucks template__
```jinja
{% for key, tag in tags %}
  display: {{ key }}
  slug: {{ tag.urlSafe }}
{% endfor %}
```

__with handlebars template__
```handlebars
{{#each tags}}
  display: {{ @key }}
  slug: {{ urlSafe }}
{{/each}}
```

As specified in README, this `tags` global identifier que be set in `opts.metadataKey`.

**Comment by hswolff** [comment]
Woohoo! Awesome!

**Comment by kanduvisla** [comment]
Perhaps I'm missing something here, but when I'm using this on a page that has tags, doesn't this just return the tags only for that page? So in other words: if a page has `tags`-metadata set, it will only be populated by the tags set for that page.

So the snippet works on pages that don't have tags set, but as soon as I'm on a page that has tags, the list is trimmed. Anyone else facing this? Sounds to me that an `allTags`-property is still welcome.
