### ISSUE TITLE
Unlisted posts with tags.

### ISSUE THREAD

**Issue by etnbrd** [totocaster/metalsmith-tags#44]
I use [`metalsmith-unlisted`](https://www.npmjs.com/package/metalsmith-unlisted) to post online posts I don't want to be public (they are not listed in the collection of posts), but still render them to share them selectively (for friends and family, for example).
And I use `metalsmith-tags`, well ... to tag those posts.

The problem :
When a post is unlisted and tagged, it doesn't appear in the list of posts, as expected.
But it still appears in the tag pages, so it becomes public (while I want it to be private).

I modified `metalsmith-tags` for this purpose, and it seems to work as expected : https://github.com/etnbrd/metalsmith-tags

But as this feature is somehow at the border between three plugins (collections, tags and unlisted), I am unsure :
 - if this feature belongs to `metalsmith-tags` (or to `metalsmith-unlisted`) at the cost of adding complexity to the existing plugin,
 - if I should clone `metalsmith-tags`, and make a new plugin with the feature (like `metalsmith-tags-unlisted`) at the cost of duplicating code, or
 - if I should make it a separate plugin (like `metalsmith-unlist-tags`), but I don't know if this is possible, given that it should modify things in the middle of the tag generation.

What you think is the good direction to take ?

Thanks.

**Comment by jarodtaylor** [comment]
As long as the following things are true, I don't see any issue with you submitting a pull request:

1. No regressive effects when  [`metalsmith-unlisted`](https://www.npmjs.com/package/metalsmith-unlisted) is **not** being used with [`metalsmith-tags`](https://github.com/totocaster/metalsmith-tags).
2. All tests still pass
3. New tests are added for the changes

**Comment by etnbrd** [comment]
I finally manage to resolve my problem without modifying `metalsmith-tags`, and created another plugin for my purpose : [`metalsmith-privileges`](https://www.npmjs.com/package/metalsmith-privileges).
It replaces the tricky workaround I had set for metalsmith-unlisted (and metalsmith-fingerprint).

I think it is the best solution, as neither `metalsmith-tags`, `metalsmith-collections` nor `metalsmith-privileges` have "hardcoded special cases" for the other two : they are completely independent. Thus, it reduces the complexity to maintain those. (Less code, less specificity, less corner-case tests, and so on)
