### ISSUE TITLE
special chars are not escaped

### ISSUE THREAD

**Issue by oupala** [totocaster/metalsmith-tags#48]
When using special chars such as the french `ç`, the chat seems to be not escaped.

Hence, when listing all document containing the tag `français`, the page `http://localhost:8080/tags/francais/` does not list the documents that contain the `français` tag but only the documents that contains the `francais` tag..

**Comment by gijswijs** [comment]
PR is merged, new version published to NPM.

**Comment by oupala** [comment]
This is a very very good news @gijswijs.

I tested the new version and it works well.

A few suggestions for the futur:

- the changelog has not been updated
- I had to add a new option (`normalize: true`) to my build file, and it was not obvious for me what was the default value of this option. I think it would be a good thing to indicate the default value of each option if not specified.

**Comment by gijswijs** [comment]
Thank you for the suggestions @oupala. I'm still trying to get into a workflow here.

Next time I will update the changelog for both this version and the new one.

Just so that I'm sure I understand you:
You would like to see the default value of all the options specified in the readme?

**Comment by oupala** [comment]
> You would like to see the default value of all the options specified in the readme?

Yes, exactly.

If the default values fits my need, I don't need to overwrite them. Otherwise, I have to had the options and their new value to the build file.
