### ISSUE TITLE
Spaces in tags are replaced by -

### ISSUE THREAD

**Issue by dpobel** [totocaster/metalsmith-tags#5]
Spaces in tags are replaced by a dash. I guess this is done on purpose to easily generate the link to the tag page.

To avoid that, I would suggest to keep the tags intact in the document while building the tags array and to build a global tags list in the Metalsmith metadata referencing the same object as the one created for `<path>/<tag>.html`. This way, if you use metalsmith-permalinks, in the template you can have access to the corresponding page URL with something like `tagsList[tag].path`.

Bonus point, this global tags list would also allow to easily create a tag cloud (I'll have to do that in a future project).

Any though on that?

**Comment by hswolff** [comment]
Hey @dpobel this sounds like a good change! 

I addressed #7 and also tackled the `metadata` issue. Care to apply the other changes in a PR?

**Comment by ronanguilloux** [comment]
@dpobel @hswolff +1 for an updated PR: nice changes to be merged here!

**Comment by hswolff** [comment]
Now resolved! Wahoo!
